<script  type="text/javascript"> tinymcefunc("insertfile undo redo styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image jbimages") </script>


<h2>login</h2>
<form  action="?page=login&action=login" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Adresse email</label>
        <input type="email" class="form-control" name="login_email" id="login_email" placeholder="Adresse email" value="<?php if(isset($email)){echo htmlentities($email);}?>">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Mot de passe</label>
        <input type="password" class="form-control" name="login_password" id="login_password" placeholder="Mot de passe">
    </div>
    <button type="submit" class="btn btn-default">Envoyer</button>
</form>
