<h2>login</h2>
<form  action="?page=login&action=login" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Adresse email</label>
        <input type="email" class="form-control" name="loginEmail" id="loginEmail" placeholder="Adresse email">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Mot de passe</label>
        <input type="password" class="form-control" name="loginPassword" id="loginPassword" placeholder="Mot de passe">
    </div>
    <button type="submit" class="btn btn-default">Envoyer</button>
</form>