<div class="row">
	<div class="rate-article">
		<h4 class="col-xs-4">Notez l'article :</h4>
		<div class="star-block col-xs-4 pull-right">
			<form action="?page=article&id=<?php echo $article['id'] ?>&action=rate" method="POST" class="text-right">
				<input type="hidden" name="id_article" value="<?php echo $article['id'] ?>">
                <span class="star-container">
                    <span class="star glyphicon glyphicon-star"><input class="star-input" type="radio" name="rating" value="5" /></span>
                    <span class="star glyphicon glyphicon-star"><input class="star-input" type="radio" name="rating" value="4" /></span>
                    <span class="star glyphicon glyphicon-star"><input class="star-input" type="radio" name="rating" value="3" /></span>
                    <span class="star glyphicon glyphicon-star"><input class="star-input" type="radio" name="rating" value="2" /></span>
                    <span class="star glyphicon glyphicon-star"><input class="star-input" type="radio" name="rating" value="1" /></span>
                </span>
			</form>
		</div>
	</div>
</div>
<script src="public/js/submit_rating.js"></script>
<hr>