<div class="row">
	<div class="rate-article">
		<h4 class="col-xs-4">Notez l'article :</h4>
		<div class="star-block col-xs-4 pull-right">
			<form action="?page=article&id=<?php echo $article['id'] ?>&action=rate" method="POST" class="text-right">
				<input type="hidden" name="id_article" value="<?php echo $article['id'] ?>">
				<input type="radio" name="rating" value="5" />5
				<input type="radio" name="rating" value="4" />4
				<input type="radio" name="rating" value="3" />3
				<input type="radio" name="rating" value="2" />2
				<input type="radio" name="rating" value="1" />1
				<button class="btn btn-default" type="submit">Submit</button>
			</form>
		</div>
	</div>
</div>
<hr>