<a title="email" href="mailto:<?php echo htmlentities($user['email']);?>" class="btn btn-default"><span class="glyphicon glyphicon-envelope"></span></a>
<a title="message privé" href="" data-toggle="modal" data-target="#msg" class="btn btn-default"><span class="glyphicon glyphicon-bullhorn"></span></a>
<?php require('./controllers/content/user/user_admin.php'); ?>

<form action="?page=user&id=<?php echo $user['id_user'];?>&action=user_messenger" method="post">
    <div class="modal fade" id="msg" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Envoyer un message privé</h4>
                </div> <!-- modal-header -->
                <div class="modal-body">
                    <div class="modal-message">
                        <input type="hidden" name="msg_id_recipient" value="<?php echo $user['id_user'] ?>">
                        <div class="form-group col-xs-12">
                            <label for="msg-subject">Sujet</label>
                            <input type="text" class="form-control" name="msg_subject" placeholder="Sujet"
                                   value="<?php if (isset($subject)) {
                                       echo htmlentities($subject);
                                   } ?>">
                        </div>
                        <div class="form-group col-xs-12">
                            <label for="msg-body">Message</label>
                            <textarea class="form-control" name="msg_content"
                                      placeholder="Votre message"><?php if (isset($content)) {
                                    echo htmlentities($content);
                                } ?></textarea>
                        </div>

                    </div>

                </div> <!-- modal-body -->
                <div class="modal-footer">
                    <div class="row">
                        <div class="col-xs-6 text-left">
                            <button type="submit" class="btn btn-success">Envoyer</button>
                        </div>
                        <div class="col-xs-6 text-right">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
                        </div>
                    </div>
                </div> <!-- modal-footer -->
            </div> <!-- modal-content -->
        </div> <!-- modal-dialog -->
    </div> <!-- modal -->
</form>