<!-- Navigation -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                MENU
            </a>
        </li>
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Category</a>
        </li>
        <li>
            <a href="#">Category</a>
        </li>
        <li>
            <a href="#">Category</a>
        </li>
        <li>
            <a href="#">Category</a>
        </li>
        <li>
            <a href="#">Category</a>
        </li>
        <li>
            <a href="#">Category</a>
        </li>
    </ul>
</div>