<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Le Blog</title>
		<link rel="stylesheet" href="public/bower_components/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="public/css/main.css">
		<script src="public/bower_components/jquery.js"></script>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/page.php'); ?>
		<?php require('apps/footer.php'); ?>
		<script src="public/bower_components/bootstrap/js/bootstrap.min.js"></script>
	</body>
</html>