<button class="btn btn-danger pull-right delete-com" data-toggle="modal" data-target="#myModal<?php echo $comment['id'];?>"  title="supprimer"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>

<div class="modal fade" id="myModal<?php echo $comment['id'];?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Supprimer le commentaire</h4>
            </div>
            <div class="modal-body">
                Confirmer la suppression du commentaire de <?php echo htmlentities($comment['user_username']);?> ?
            </div>
            <div class="modal-footer">
                <form method="post" action="<?php echo '?page=article&id='.intval($_GET['id']).'&action=comment_delete' ?>">
                    <input type="hidden" name="id" value="<?php echo $comment['id'];?>">
                    
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    <button type="submit" class="btn btn-danger">Confirmer</button>
                </form>
            </div>
        </div>
    </div>
</div>
