<!-- Comment -->
    <hr>
    <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="" alt="">
        </a>

        <div class="media-body">

            <blockquote>

                <footer>

                    <div class="col-xs-6">
                       <span class="glyphicon glyphicon-time"></span> Ecrit le <?=date("jS M Y G:i", strtotime($comment['comments_date']))?>
                    </div>

                    <col-xs-6>
                       <span class="glyphicon glyphicon-edit"></span> Auteur: <a href="?page=user&amp;id=<?= $article['id_user'] ?>"> <?= htmlentities($comment['user_username']) ?></a>
                    </col-xs-6>

                </footer>

            </blockquote>

            <p><?=htmlentities($comment['comments_content'])?></p>
        
        </div>
    </div>