<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Voir
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <li><a href="?page=home&amp;p=5&amp;o=0">5 articles par page</a></li>
        <li><a href="?page=home&amp;p=10&amp;o=0">10 articles par page</a></li>
        <li><a href="?page=home&amp;p=15&amp;o=0">15 articles par page</a></li>
    </ul>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- Blog Post -->
            <?php require('./controllers/content/home/home_list.php');?>
        </div>
    </div>
</div>