
<h2>Boîte de réception</h2>
<div class="container">
	<div class="row">
		
	</div>
	<div class="row">
		<h3>Rédiger un message</h3>
		<form action="?page=messenger&action=messenger" method="POST">
			<div class="form-group col-xs-12 col-sm-6">
				<label for="msg-subject">Sujet</label>
				<input type="text" class="form-control" name="msg_subject" placeholder="Sujet" value="<?php if(isset($subject)){echo htmlentities($subject); }?>">
			</div>
			<div class="form-group col-xs-12 col-sm-6">
				<label for="msg-recipient">Destinataire</label>
				<input type="text" class="form-control" name="msg_recipient" placeholder="Destinataire"  value="<?php if(isset($recipient)){echo htmlentities($recipient); }?>">
			</div>
			<div class="form-group col-xs-12">
				<label for="msg-body">Message</label>
				<textarea class="form-control" name="msg_content" placeholder="Votre message"><?php if(isset($content)){echo htmlentities($content); }?></textarea>
			</div>
			<div class="col-sm-12">
				<button type="submit" class="btn btn-default">Envoyer</button>
			</div>
		</form>
	</div> <!-- row -->
	<div class="row">
		<h3>Messages reçus</h3>
		<div class="table-responsive">
			<table class="table">
				<colgroup>
					<col span="1" style="width: 25%;">
					<col span="1" style="width: 55%;">
					<col span="1" style="width: 20%;">
				</colgroup>
				<thead>
					<th>Date</th>
					<th>Sujet</th>
					<th>Auteur</th>
				</thead>
				<tbody>
					<?php require('controllers/content/messenger/messenger_inbox.php') ?>
				</tbody>
			</table>
		</div>
	</div> <!-- row -->
</div> <!-- container -->