<!-- Navigation -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                MENU
            </a>
        </li>
        <li>
            <a href="?page=home">Home</a>
        </li>
        <?php require('./controllers/menu/menu_visitor.php');?>
        <?php require('./controllers/menu/menu_member.php');?>
        <?php require('./controllers/menu/menu_admin.php');?>
    </ul>
</div>