<header class="header">
    <div class="row">
        <div class="col-xs-2 icon-menu">
            <a href="#menu-toggle" id="menu-toggle">
                <span class="glyphicon glyphicon-menu-hamburger"
                      aria-hidden="true"></span>
            </a>
        </div>
        <div class="col-xs-10">
            <div class="col-xs-11">
                <h1><a href="index.php">Blog title</a></h1>
            </div>
        </div>
    </div>
</header>

