<div class="container">	
	<div class="row">
		<h3>Utilisateurs</h3>
		<div class="table-responsive">
			<table class="table">
				<thead>
					<th>Pseudo</th>
					<th>Email</th>
					<th>Date d'inscription</th>
					<th>Droits</th>
					<th>Update</th>
				</thead>
				<tbody>
					<?php require('controllers/content/user_list/user_list_user.php') ?>
				</tbody>
			</table>
		</div>
	</div> <!-- row -->
</div> <!-- container -->