<tr>
	<td><?php echo $user['username'] ?></td>
	<td><?php echo $user['email'] ?></td>
	<td><?php echo $user['date_register'] ?></td>
	<form action="?page=user_list&action=user_update_status" method="POST">
		<input type="hidden" name="id_user" value="<?php echo $user['id'] ?>">
		<td>
			<select name="status" class="form-control">
				<option <?php if ($user['status'] == '-2'){echo("selected");}?> value="-2">Permaban</option>
				<option <?php if ($user['status'] == '-1'){echo("selected");}?> value="-1">Ban</option>
				<option <?php if ($user['status'] == '1'){echo("selected");}?> value="1">Standard</option>
				<option <?php if ($user['status'] == '2'){echo("selected");}?> value="2">Admin</option>
			</select>
		</td>
		<td><button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button></td>
	</form>
</tr>