<!-- Blog Post Content Column -->

    <!-- Blog Post -->

    <!-- Title -->
    <h2><?=htmlentities($article['title'])?></h2>

    <!-- Author -->
    <p class="lead">
        by <a href="#"><?=htmlentities($article['username'])?></a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted on <?= date("jS M Y", strtotime($article['date_published']))?></p>

    <hr>

    <!-- Preview Image -->
    <img class="img-responsive" src="http://placehold.it/1200x300" alt="">

    <hr>

    <!-- Post Content -->
    <p class="lead"><?=htmlentities($article['content'])?></p>

    <hr>

    <!-- Blog Comments -->

    <!-- Comments Form -->

    <?php 
    require('./controllers/content/article/article_comment_form/article_comment_form.php');
     ?>    

     <!-- Posted Comments -->

     <?php 
    require('./controllers/content/article/article_comment_list/article_comment_list.php');
     ?>