<!-- Blog Post Content Column -->


    <!-- Blog Post -->

    <!-- Title -->
    <h2><?=$article['title']?></h2>

    <!-- Author -->
    <p class="lead">
        by <a href="#"><?=$article['username']?></a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted on <?=$article['date_published']?></p>

    <hr>

    <!-- Preview Image -->
    <img class="img-responsive" src="http://placehold.it/1200x300" alt="">

    <hr>

    <!-- Post Content -->
    <p class="lead"><?=$article['content']?></p>

    <hr>

    <!-- Blog Comments -->

    <!-- Comments Form -->
    <div class="well">
        <h4>Leave a Comment:</h4>

        <form role="form">
            <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <hr>

    <!-- Posted Comments -->

    <!-- Comment -->
    <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="" alt="">
        </a>

        <div class="media-body">
            <h4 class="media-heading"><!-- Titre article -->
                <small><!-- Date commentaire --></small>
            </h4>
            <!-- Texte commentaire -->
        </div>
    </div>

    <!-- Nested Comment -->
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="" alt="">
                </a>

                <div class="media-body">
                    <h4 class="media-heading"><!-- Nested titre article -->
                        <small><!-- Date commentaire --></small>
                    </h4>
                    <!-- Texte commentaire -->
                </div>
            </div>
            <!-- End Nested Comment -->
        </div>
    </div>