<div>
	<!-- Blog Post Content Column -->
<div class="col-lg-8">

    <!-- Blog Post -->

    <!-- Title -->
    <h2><a href="?page=article&amp;id=<?=$article['id']?>"><?=$article['title']?></a></h2>

    <!-- Author -->
    <p class="lead">
        by <a href="#"><?=$article['username']?></a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted on <?=$article['date_published']?></p>

    <hr>

    <!-- Preview Image -->
    <img class="img-responsive" src="http://placehold.it/900x300" alt="">

    <hr>

    <!-- Post Content -->
    <p class="lead"><?=$article['content']?></p>

    <hr>
</div>
</div>