<div class="row">
	<div class="col-sm-6">
		<table id="myTable" class="table table-striped tablesorter">
			<thead>
				<td class="headerSortUp headerSortDown">Pseudo <i class="fa fa-sort"></i></td>
				<td class="headerSortUp headerSortDown">Nombre d'articles postés <i class="fa fa-sort"></i></td>
			</thead>
			<tbody>
				<?php 
				require('./controllers/content/users_view/users_view_li.php');
				 ?>	
			</tbody>
		</table>			
	</div>
</div>